version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
        bash -c "python manage.py runserver 0.0.0.0:9001"
    volumes:
      - .:/code
    ports:
      - 9001:9001
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    command: "celery -A django_api worker -l DEBUG"
    depends_on:
      - django
      - rabbitmq

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9091:9090"

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
