# Generated by Django 4.1.1 on 2022-10-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_request_test_file_alter_result_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='test_file',
        ),
        migrations.AlterField(
            model_name='request',
            name='file_name',
            field=models.FileField(default='', upload_to='resources/'),
        ),
    ]
